# Generated by Django 5.2 on 2025-05-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0002_alter_usernotes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotes',
            unique_together=set(),
        ),
    ]
