# Generated by Django 5.2 on 2025-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0004_revisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
