"""
Django settings for freelance_taskboard project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1tuu39^b0%%of2m9k2k_1a!1kio23r%onz@i+#99j03z55dd*3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# # ─── Environment Config 
# ENVIRONMENT = os.getenv("ENVIRONMENT", "LOCAL")
# LOCAL = os.getenv("LOCAL", "True") != "False"
# DEBUG = os.getenv("DEBUG", "True") != "False"
# OSX = os.getenv("OSX", "WIN")


# # ─── Domain Configuration
# PRIMARY_DOMAIN = os.getenv("PRIMARY_DOMAIN", "freelancetaskboard.localhost")
# SUBDOMAIN_HOST = os.getenv("SUBDOMAIN_HOST", "localhost")
# FULL_HOST_LINK = os.getenv("FULL_HOST_LINK", f"http://{PRIMARY_DOMAIN}:8000")
# DJANGO_SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# HTTP_PROTOCOL = os.getenv("HTTP_PROTOCOL", "http")

ALLOWED_HOSTS = ['freelancetaskboard.com', 'localhost', '127.0.0.1']

# if ENVIRONMENT == "LOCAL":
#     ALLOWED_HOSTS = ['localhost', '127.0.0.1', f'.{SUBDOMAIN_HOST}', '*']
# elif ENVIRONMENT == "TEST":
#     ALLOWED_HOSTS = [".testdomain.com"]
# elif ENVIRONMENT == "PRODUCTION":
#     ALLOWED_HOSTS = ["your-production-domain.com", f".{SUBDOMAIN_HOST}"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'channels',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # Local Apps
    'Accounts.apps.AccountsConfig',
    'Tasks.apps.TasksConfig',
    'Billing.apps.BillingConfig',
    'Scheduling.apps.SchedulingConfig',
    'Notifications.apps.NotificationsConfig',
    'Coresystem.apps.CoresystemConfig',
    'Interactions.apps.InteractionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Coresystem.middleware.DashboardAuthMiddleware',
]


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.SessionAuthentication',
#     ),
# }

ASGI_APPLICATION = "freelance_taskboard.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },

# }


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'


INVALID_DOMAIN_CSV = os.path.join(BASE_DIR, "Coresystem/securityfiles/temp_domains.csv")

ROOT_URLCONF = 'freelance_taskboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freelance_taskboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'freelance-taskboard',
        'USER': 'postgres',
        'PASSWORD':'1234',
        'HOST':'localhost'
    }
}

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'
EMAIL_HOST_PASSWORD = 'your_app_password_or_password'
DEFAULT_FROM_EMAIL = 'Your Project <your_email@gmail.com>'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'Accounts.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT =  os.path.join(BASE_DIR, 'static')
STATICFILES_DIR = (
    os.path.join(BASE_DIR,'Accounts', 'static'),
    os.path.join(BASE_DIR,'Tasks', 'static'),
    os.path.join(BASE_DIR,'Billing', 'static'),
    os.path.join(BASE_DIR,'Scheduling', 'static'),
    os.path.join(BASE_DIR,'Notifications', 'static'),
    os.path.join(BASE_DIR,'Coresystem', 'static'),
    os.path.join(BASE_DIR,'Interactions', 'static'),
)

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
