# Generated by Django 5.2 on 2025-04-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coresystem', '__first__'),
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coresystem.authtokens')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Tasks.task')),
            ],
        ),
    ]
