# Generated by Django 5.2 on 2025-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
