# Generated by Django 5.2 on 2025-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0011_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
