# Generated by Django 5.2 on 2025-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coresystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokens',
            name='auth_type',
            field=models.IntegerField(choices=[(1, 'Verify Sign Up'), (2, 'Login'), (3, 'Password Reset'), (4, 'Invitation')]),
        ),
    ]
